### ISSUE TITLE
Upgrade in Odoo 15

### ISSUE THREAD

**Issue by caygri** [MultiSafepay/official-odoo-integration#1]
Hello,

is on the way the updating of module for new version of odoo?

**Comment by danielcivit** [comment]
Hello @caygri, sorry for the long time without reply to this issue. Somehow it was out of our radar. 

Unfortunately we have no plans to support the latest version of Odoo 15 in the next few weeks - months.
Of course, this may change at some point; in which case our staff will contact you to let you know.

Thanks.
